### ISSUE TITLE
Retrieval and Indication of Selected Landmarks for a Trip

### ISSUE THREAD

**Issue by jadmalek** [amawai/android-wikipedia-390#101]
Task of US #70.

[Story Points: 2] - 1 per assignee
[Risk: Medium]
[Priority: High]

**Comment by amawai** [comment]
**Acceptance Testing**

| Test #         | Inputs | Expected Output  | Status |
| ------------------ | ------------- | ------------- | ------------- |
| 1. Plan a Trip card appears on application's main page.  | Wikipedia application launched.  | A card for the trip planner is displayed, along with the other cards, on the main page.  | PASS  |
| 2. Plan a Trip page display.  | Press on Plan a Trip arrow icon on card.  | The Plan a Trip page is depicted, including a list of trips and the option to plan a new trip.   | PASS  |
| 3. Destination picker display.  | Press on the "+ Plan a new trip" button. | Destinations page is depicted, including a search bar for a destination to be inputted.   | PASS  |
| 4. Particular destination selection.  | Type in the name of the destination and select on the dropdown menu, or simply click on the dropdown menu and select a desired destination. | Selected destination will appear in text format above the search bar.   | PASS  |
| 5. Particular destination selection.  | Type in the name of the destination and select on the dropdown menu, or simply click on the dropdown menu and select a desired destination. | Selected destination will appear in text format above the search bar.   | PASS  |
| 6. Particular destination selection.  | Pick a date from the calendar that pops up upon clicking the "Select Date" button. | Selected date will appear above the "Select Date" button.   | PASS  |
| 7. Landmarks page display.  | Select the next (arrow) icon. | Landmarks for the selected destination appear, where each landmark has a checkbox next to it.   | PASS  |
| 8. View landmarks articles.  | Click on any of the landmark. | Article page corresponding to that landmark is displayed.   | PASS  |
| 9. Save landmarks.  | Check off boxes of desired landmarks. | "Trip has been saved" message is displayed.   | PASS  |
| 9. Check that saved landmarks are indicated as such in landmarks screen.  | Select on edit ("pencil") icon to modify a saved planned trip and select on next button in each of the screens of the trip planner until the landmarks screen is displayed. | Previously saved landmarks will have checks in the corresponding checkboxes. | PASS  |


**Demo Steps**

1. Launch the application.
2. Scroll down the main page until the Plan a Trip card is visible.
3. Press on the Plan a trip arrow icon to view the Plan a Trip screen.
4. Press on the "+ Plan a new trip" button in order to begin planning a new trip.
5. Enter a particular destination.
6. Press the next button.
7. Pick a particular Departure Date from the "Select Date" calendar.
8. Press the next button.
9. Click on a landmark.
10. Press back to return to the destination's Landmarks screen.
11. Select landmark checkboxes.
12. Select the Save button.
13. Press back until on main page of application.
14. Select on the edit ("pencil") of most recently planned trip.
15. Press next button on destination and date screens to get to the landmarks screen.
16. Confirm that the selected landmarks are checked off, indicating that these are the desired landmarks for the trip. 

Closed by #110
